########################### SERVICES
services:
  ########################### ROBOTNIK LABS CLIENT
  robotnik-labs:
    image: robotnik-labs
    container_name: robotnik-labs
    build:
      context: ./
      dockerfile: Dockerfile-robotnik
    environment:
      - TZ=America/Sao_Paulo
    ports:
      - "8111:80"
    labels:
      # Traefik Config
      - "traefik.enable=true"
      - "traefik.http.routers.robotnik-labs.tls=true"
      - "traefik.http.routers.robotnik-labs.rule=Host(`robotnik-labs.app.pb.utfpr.edu.br`)"
      - "traefik.http.routers.robotnik-labs.tls.certresolver=letsencrypt"
      - "traefik.http.routers.robotnik-labs.entrypoints=websecure"

    restart: unless-stopped
    networks:
      - web

########################### NETWORKS
networks:
  web:
    external: true
