########################### SERVICES
services:
  ########################### DAELE LABS CLIENT
  daele-labs:
    image: daele-labs
    container_name: daele-labs
    build:
      context: ./
      dockerfile: Dockerfile-daele
    environment:
      - TZ=America/Sao_Paulo
    ports:
      - "8111:80"
    labels:
      # Traefik Config
      - "traefik.enable=true"
      - "traefik.http.routers.daele-labs.tls=true"
      - "traefik.http.routers.daele-labs.rule=Host(`daele-labs.app.pb.utfpr.edu.br`)"
      - "traefik.http.routers.daele-labs.tls.certresolver=letsencrypt"
      - "traefik.http.routers.daele-labs.entrypoints=websecure"

    restart: unless-stopped
    networks:
      - web

########################### NETWORKS
networks:
  web:
    external: true
