########################### SERVICES
services:
  ########################### patobots LABS CLIENT
  patobots-labs:
    image: patobots-labs
    container_name: patobots-labs
    build:
      context: ./
      dockerfile: Dockerfile-patobots
    environment:
      - TZ=America/Sao_Paulo
    ports:
      - "8121:80"
    labels:
      # Traefik Config
      - "traefik.enable=true"
      - "traefik.http.routers.patobots-labs.tls=true"
      - "traefik.http.routers.patobots-labs.rule=Host(`patobots-labs.app.pb.utfpr.edu.br`)"
      - "traefik.http.routers.patobots-labs.tls.certresolver=letsencrypt"
      - "traefik.http.routers.patobots-labs.entrypoints=websecure"

    restart: unless-stopped
    networks:
      - web

########################### NETWORKS
networks:
  web:
    external: true
