version: "3.9"

########################### SERVICES
services:
  ########################### DAINF LABS CLIENT    
  dainf-labs-client:        
    image: dainf/dainf-labs-client:prod
    container_name: dainf-labs-client
    build:
      context: .
      dockerfile: Dockerfile
    labels:
    # Traefik Config
      - "traefik.enable=true"
      - "traefik.http.routers.dainf-labs-client.rule=Host(`dainf-labs.app.pb.utfpr.edu.br`)"
      - "traefik.http.routers.dainf-labs-client.entrypoints=websecure"
      - "traefik.http.routers.dainf-labs-client.certresolver=letsencrypt"
    environment:
      - TZ=America/Sao_Paulo
    ports:
      - "8098:80"      
    restart: unless-stopped
    networks:
      - web
      - database

########################### NETWORKS
networks:
  web:
    name: web
    driver: bridge
    external: true
    attachable: true
  database:
    name: database
    driver: bridge
    external: false
    attachable: true