version: "3.9"

########################### SERVICES
services:
  ########################### DAINF LABS CLIENT    
  dainf-labs:        
    image: dainf-labs
    container_name: dainf-labs
    build:
      context: ./
      dockerfile: Dockerfile    
    environment:
      - TZ=America/Sao_Paulo
    ports:
      - "8098:80"      
    labels:
      # Traefik Config
      - "traefik.enable=true"
      - "traefik.http.routers.dainf-labs.tls=true"
      - "traefik.http.routers.dainf-labs.rule=Host(`dainf-labs.app.pb.utfpr.edu.br`)"
      - "traefik.http.routers.dainf-labs.tls.certresolver=letsencrypt"
      - "traefik.http.routers.dainf-labs.entrypoints=websecure"      
    
    restart: unless-stopped
    networks:
      - web

########################### NETWORKS
networks:
  web:
    external: true